### ISSUE TITLE
Special Characters are wrong

### ISSUE THREAD

**Issue by EorlBruder** [firecat53/keepmenu#10]
I added an entry (via keepasx2) to my database, where the pasword ist `???`. Keepmenu does output `&&&` in that case. 

I also tried other special characters and they all get transformed into other special characters.

**Comment by firecat53** [comment]
I'm going to need some more details. I've tried adding numerous special and non-english characters to the password field from both keepassx2, keepassxc and keepmenu, and they are saved and displayed correctly in all cases. If you can perhaps email me a keepass database with a few entries that have the problem and/or post some screenshots that show what you are seeing, that would be helpful.

I'd also recommend switching to keepassxc as it is an up-to-date fork. I don't believe keepassx2 is being maintained anymore.

**Comment by EorlBruder** [comment]
I tried the same database in keepassxc and it worked as expected. I then created a new database in keepassxc (as the one I use is very old) and I got the same error. 

I attached the database in question to this comment. The password is "test". There is only one entry in it which should have "???" as the password, but keepmenu shows the password as "&&&".


[database.tar.gz](https://github.com/firecat53/keepmenu/files/2385788/database.tar.gz)

**Comment by firecat53** [comment]
Hmmm, works fine here. I'm suspecting a locale issue, so I'll need more information (and it might help you narrow down the problem, too).

- What distro?
- How did you install keepmenu?
- Python 2 or 3  (if you're using python 2, please try 3 if you can)
- Output of `localectl` if your distro supports it
- `grep -v "^#" /etc/locale.conf`
- `env | grep LANG`

**Comment by EorlBruder** [comment]
I'm using Arch Linux and installed keepmenu via the AUR-package python-keepmenu-git (which uses python 3). 
```
#localectl                                                                                                                                 
System Locale: LANG=en_US.UTF-8                                                                                                                                  
LC_NUMERIC=de_DE.UTF-8                                                                                                                                                     LC_TIME=de_DE.UTF-8                                                                                                                                LC_MONETARY=de_DE.UTF-8                                                                                                                            LC_PAPER=de_DE.UTF-8                                                                                                                               LC_MEASUREMENT=de_DE.UTF-8                                                                                                                         VC Keymap: de                                                                                                                                                 X11 Layout: de     
```
```
#grep -v "^#" /etc/locale.conf 
LANG=en_US.UTF-8                                                                                                                                                     LC_NUMERIC=de_DE.UTF-8                                                                                                                                               LC_TIME=de_DE.UTF-8                                                                                                                                                  LC_MONETARY=de_DE.UTF-8                                                                                                                                              LC_PAPER=de_DE.UTF-8                                                                                                                                                 LC_MEASUREMENT=de_DE.UTF-8    
```
```
#env | grep LANG
LANG=en_US.UTF-8 
```

**Comment by firecat53** [comment]
Definitely confirmed the bug! Now I just have to figure out how to fix it. Thanks for the report!

**Comment by firecat53** [comment]
Ok, it's obviously been a long time since I wrote this tool. I failed to read my own README.

You need to call `set xkbmap de` someplace in your window manager startup, install xdotool, and then set `type_library = xdotool` in ~/.config/keepmenu/config.ini. That immediately solved it for me in the VM I spun up to duplicate your issue.

So...thanks for reminding me to read my own README first. Let me know if that works for you.

**Comment by EorlBruder** [comment]
Thanks, that solved it for me. 
Sorry for not having read the README first myself.
