### ISSUE TITLE
Fuzzy search doesn't find certain entries

### ISSUE THREAD

**Issue by ndcontini** [firecat53/keepmenu#102]
There are a few password entries that keepmenu doesn't seem to find when I type in perfectly matching search terms. For example, I have a group of entries called "Benefits" and there is an entry named "United Healthcare". When I type "United" keepmen displays only one match, United Airlines, but not United Healthcare. This behavior seemed to start when the AUR package last updated. Let me know what debug info you might need.

**Comment by firecat53** [comment]
I'm not at my computer right now, but I would check that you updated your config.ini with the `-i` flag in `dmenu_command`, as that is no longer automatically added.

**Comment by ndcontini** [comment]
That was the problem. Thanks for pointing that out!
