### ISSUE TITLE
Launching URLs in web browser has stopped working for me

### ISSUE THREAD

**Issue by aclindsa** [firecat53/keepmenu#106]
I am not entirely sure what is at fault here, but I have noticed recently that when I hit [Enter] while over a URL for an entry under "View/Type Individual entries", the text of URL is inserted in whichever window is currently focused, instead of the expected behavior of opening in my default web browser.

I am using dmenu, if that matters.

I have looked through the documentation, and have been unable to find anything suggesting that configuration for this feature has changed recently. Am I missing something?

**Comment by firecat53** [comment]
Fixed, thanks for the report!

**Comment by aclindsa** [comment]
@firecat53 Thank you for your project and quick response!
