### ISSUE TITLE
some usability requests

### ISSUE THREAD

**Issue by zeltak** [firecat53/keepmenu#11]
Thx for this great app

I have some requests to make keepmenu work similarly to rofi-pass which is very advanced 

 1) dont hit enter by default? again for security reasons
2) establish a standard for autotype sequences similar to rofi-pass perhaps?
3) a way to type certain fields, like password only or username onlye.g. useful for git prompts

thx so much!

Z

**Comment by firecat53** [comment]
1. I can maybe make this configurable
2. If I implemented this, I'd use the same pattern as [keepassxc](https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence)
3. You can can already do this 2 ways: first, if you only assign a password (or only assign a username), that will be autotyped by default when selected. Second, hit enter initially to select "View/Type Individual entries", then select your entry, then select the field to type.

Thanks for the interest!

**Comment by carnager** [comment]
Autotype sequences would be great. Plus maybe a dialog to edit them.

**Comment by firecat53** [comment]
I think all these are addressed by the latest updates. You can now edit autotype sequences from within Keepmenu. You do need a very recent git version of pykeepass, however (after Nov 6th 2018). Easiest way right now is to clone their repo and then `pip install --user -e .`.
