### ISSUE TITLE
Some TOTP entries are not working

### ISSUE THREAD

**Issue by seidler2547** [firecat53/keepmenu#117]
For some of my database entries there is no TOTP value generated. But KeepassXC can generate it and when I use keepmenu to "View/Type individual entries" and go to the entry, I can see two fields "TOTP Seed" and "TOTP Settings", but the "TOTP" field is empty.

**Comment by firecat53** [comment]
Can you please post both working and non-working values (feel free to randomize numbers/urls, etc, I'm more looking at the format) for the TOTP Seed field?

**Comment by seidler2547** [comment]
I think where it works is when the attribute `otp` is present, using the format `otpauth://totp/blah?secret=SUPERSECRET&period=30&digits=6` and where it doesn't work it has two fields, one called `TOTP Seed` with the secret and one called `TOTP Settings` with the value `30;6`.

**Comment by firecat53** [comment]
That would make sense. Keepmenu only processes the first url-style format.
Can you create a test .kdbx database with one working entry and a couple of
the non-working entries so I can look at the actual field names/values that
will need to be processed? Thanks!

**Comment by seidler2547** [comment]
Here's the file. Password is `password`
All "Test TOTP" entries should generate the same token and all "Other TOTP" entries as well.
[TOTP-Test.zip](https://github.com/firecat53/keepmenu/files/8864897/TOTP-Test.zip)

**Comment by firecat53** [comment]
Give the `totp` branch a try and see if that works for you. Thanks for the detailed info and the sample kdbx file! Made solving this significantly easier!

**Comment by bdeshi** [comment]
> @firecat53 some additional formats to detect:

here's a demo db with samples of both.
[Database.zip](https://github.com/firecat53/keepmenu/files/9100730/Database.zip)

**Comment by bdeshi** [comment]
@firecat53 also, I should note, the "TOTP Seed", "TOTP Settings" fields were introduced by keepass2's [KeeTrayTOTP](https://github.com/KeeTrayTOTP/KeeTrayTOTP) & [TrayTOTP](http://sourceforge.net/projects/traytotp-kp2/) plugins. Keepassium just implemented support for this convention in their application.

**Comment by bdeshi** [comment]
> @firecat53 some additional formats to detect:
> 
>  * the original keepass2 has its own totp feature comprised of [distinct entry fields and autotype triggers](https://keepass.info/help/base/placeholders.html#otp).
>  keepass2 can in fact import `otpauth://` strings into this fieldset.
> 
>  * keepass2's [keeotp](https://github.com/tiuub/KeeOtpMirror) / [keeotp2](https://github.com/tiuub/KeeOtp2) plugins can use a slightly different format for the `otp` field.
>  this is partially supported by keepassxc (and I myself have a lot of entries with this format sweat_smile)

@firecat53 i can work on adding support for these, should i work on top of the `totp` branch?

**Comment by firecat53** [comment]
That would be great! I've got family coming in this weekend so time will be limited for awhile. Let me know if you have implementation questions and please add tests as well. Thanks!

**Comment by firecat53** [comment]
@seidler2547 Please test if the new OTP support works for you. Thanks!

**Comment by seidler2547** [comment]
@firecat53 sorry for the delay, my use cases work fine now. Thanks!
