### ISSUE TITLE
a way to remember password/key for a user defined time?

### ISSUE THREAD

**Issue by zeltak** [firecat53/keepmenu#12]
Been using keepmenu over the last few days and really love it

but it seems that each time i launch it i have to enter again my password/key 

is it possible to remember the password for X minutes (or user defined period) so i dont have to re-enter the password 20 times an hour :D 

thx!

Z

**Comment by firecat53** [comment]
Set pw_cache_period_hrs in config.ini. The default is 6 hours, so I'm surprised you're having to enter it multiple times per day, unless it's being killed/restarted somehow.

**Comment by zeltak** [comment]
got it. i was testing via command line and then after selecting the entry pressed C-c to quit. binding it to a key does indeed keep the pass cached

thx

Z

**Comment by firecat53** [comment]
Sorry, and it's pw_cache_period_min, not hrs. I've gotta update the README!
