### ISSUE TITLE
[Request] add option to type URL alongside view, edit and launch

### ISSUE THREAD

**Issue by elg3a** [firecat53/keepmenu#135]
Hi there,

thank you so much for this amazing tool, I use it every day!

As the title says, it would be useful to have the url typed out just like the username or password (E.g., in situations with multiple/non-default browsers). If I understand correctly, this was changed to resolve issue #14? An option to make this configurable would be awesome.

Thanks for considering!

**Comment by firecat53** [comment]
PR merged, thanks!
