### ISSUE TITLE
[Request] add option to launch URL alongside view and edit

### ISSUE THREAD

**Issue by zeltak** [firecat53/keepmenu#14]
Hi again

suggesting another cool usability addition where alongside the view and edit entries there would be an option to launch entry URL (like the keepass/keepassXC) `open url` bind.

best

Z

**Comment by firecat53** [comment]
Give the develop branch a try. I modified it so the URL is opened in the default browser instead of typed when selected from the 'View/Type' view.

**Comment by zeltak** [comment]
works great!

thx
