### ISSUE TITLE
After update keepmenu started to incorrectly type `|` as `>`

### ISSUE THREAD

**Issue by pr0sp3ro** [firecat53/keepmenu#140]
After updating keepmenu and using it I started to get errors about entering wrong passwords on sites. Turns out keepmenu is replacing `|` symbol with `>`.

**Comment by vaygr** [comment]
A couple of questions:
- what was the previous version and what's the new one?
- what is the auto-type method (pynput, xdotool, ydotool, wtype)?

**Comment by pr0sp3ro** [comment]
pynput was used, now after a change to xdotool it's working corretly. Sorry, I didn't think this could be a issue.

**Comment by firecat53** [comment]
No worries! I'm not sure if you're using US English keyboard, but xdotool is the only one that will work with non-English layouts. It's in the documentation, but I know there's a lot of words in there, so easy to miss!

**Comment by vaygr** [comment]
Now I've faced this bug myself. Using pynput keepmenu turned password `.....|..........` into `.....>..........`. Regular US English kb/layout here.

**Comment by firecat53** [comment]
I'm very tempted to remove pynput but it does provide a low barrier for people testing keepmenu for the first time without any additional configuration or tools.

**Comment by vaygr** [comment]
Should we report this behavior to pynput? I feel like this is a great dependency-less option to keep.

**Comment by firecat53** [comment]
That would prob be good. Sure be nice if they also supported wayland! I tried the uinput backend and even though my /dev/uinput has `rw-rw---- 1 root users`, and my user is part of users group, it still wanted root permissions.

In any case, I don't use X so it'll be awhile before I get around to switching and gathering enough info for a bug report. If you have the capacity, please do so!
