### ISSUE TITLE
FYI: dotool

### ISSUE THREAD

**Issue by johngebbie** [firecat53/keepmenu#143]
Hi, you might like [dotool](https://git.sr.ht/~geb/dotool), which is a uinput tool like ydotool but doesn't require root or a daemon and can use key names instead of key codes.

**Comment by vaygr** [comment]
Excellent minimalist tool, thank you @JohnGebbie!

**Comment by JohnGebbie** [comment]
Glad you like it :) I just pushed support to simulate keycodes for different keyboard layouts yesterday.

**Comment by vaygr** [comment]
@JohnGebbie while we're at it, I was wondering if it'd be possible to add typing simulation for unicode characters and sequences (like emojis) or this is something that can be solved only via X primitives (like `xtest` extension).

**Comment by JohnGebbie** [comment]
No I'm afraid, dotool/uinput can only simulate keycodes so there's not much hope for that as far as I know.

**Comment by firecat53** [comment]
I've added support for dotool. If you could test the development branch I'd appreciate it! Definitely doesn't work well with special characters. Thanks!
