### ISSUE TITLE
flake: hatch-vcs not working

### ISSUE THREAD

**Issue by mraethel** [firecat53/keepmenu#147]
When including the flake as `inputs.keepmenu.url = "github:firecat53/keepmenu"` and using its package in `environment.systemPackages = [ keepmenu.packages.${system}.default ]` nix complains:

```
Processing /build/source
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/hlv2dcs318ka1p9wv4gqh7z77q5m8zm9-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/hlv2dcs318ka1p9wv4gqh7z77q5m8zm9-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/hlv2dcs318ka1p9wv4gqh7z77q5m8zm9-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
      return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
      self.metadata.validate_fields()
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
      _ = self.version
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 128, in version
      self._version = self._get_version()
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 226, in _get_version
      version = self.hatch.version.cached
    File "/nix/store/hllpkkgfp9mn6nrl8mlq0qzb3l3wbvh2-python3.10-hatchling-1.13.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1412, in cached
      raise type(e)(message) from None
  LookupError: Error getting the version from source `vcs`: setuptools-scm was unable to detect version for /build/source.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

The source directory in the nix store doesn't contain a .git directory, which is required by hatch-vcs.
Cloning to a local directory and including as `inputs.keepmenu.url = "path:path/to/repo-with-git"` works.

Possible solutions:
 1. Using `fallback-version` under `[ tool.hatch.version ]` in `pyproject.toml`.
 2. Using `fetchFromGithub` with option `leaveDotGit = true` as `src` in `flake.nix`.
 3. Not using hatch-vcs.

Are there any other options?

**Comment by firecat53** [comment]
I [struggled with this](https://discourse.nixos.org/t/help-with-python-flake-build-from-local-source/30140/1) when initially writing the flake.

In the end, I decided that the use case for the flake was development. Keepmenu is packaged in nixpkgs, so there's not a good reason (in my mind) to have the flake available to run the development version without having the source on the local machine.

1. `fallback-version` had other undesirable side effects (see the discourse discussion)
2. I don't think I tried this. Does it meet the goals of being able to use the flake for `nix run`, `nix shell` and `nix develop` for local development and testing?
3. But hatch is just realllly convenient for development (for non-nix folks) and for publishing to Pypi! 

Read through the discourse discussion and see if anything else pops out at you.

Thanks!

**Comment by mraethel** [comment]
To give some reasoning: The nixpkgs source is dependent on PyPI. If a feature is not covered by a release yet it can't be utilized by neither a simple nixpkgs src-overlay nor the flake without keeping a local clone.

Concerning 1: After reading through the discussion I think setting `fallback-version` to something like `0.0.0` is not a problem since to my knowledge it's not relevent to `nix run` or `nix shell` and correct when developing with `nix develop`.
I am not sure what is ment by it being "sketchy".
Concerning 2: On second thought this only works if we have two packages: A default and a development package with `src = fetchFromGithub ...` and `src = self` respectively. Using `fetchFromGithub` however is not ideal as we would end up having the same source twice in the nix store with the only difference being the `.git` directory.
Concerning 3: I agree.

This leaves 1 as the best option.
Else I am happy to wait for the next release.

**Comment by firecat53** [comment]
For now I released 1.4.0. I'll try to be better about releases this year!

When I get a chance, I'll test the fallback-version option again and see if setting it to `0.0.0` has any side effects.

**Comment by vaygr** [comment]
Yeah, this creates real obstacles for proper packaging in distributions, since scm versions are almost never packaged. AUR is an exception. But for wider adoption building from a tarball should be easy.

I recently updated the [non-git version](https://aur.archlinux.org/packages/keepmenu) in AUR by simply [adding](https://aur.archlinux.org/cgit/aur.git/commit/?h=keepmenu&id=b6c4312066ce3b4c89219f8830616d52069f3c20) `fallback-version`.

**Comment by firecat53** [comment]
Ok, I added `fallback-version = "0.0.0"`. That seems to allow the normal use of `hatch build`, `nix build path:.`, and `nix develop path:.`.

I've just kept it on the `devel` branch for now. Can you test and see if you can break something?

My input: `keepmenu.url = "github:firecat53/keepmenu/develop";`.

Thanks!

**Comment by mraethel** [comment]
I couldn't find any issues with this. Thanks for updating!

FYI: `nix develop` already works without the `path:.` argument.

For the long term it is maybe possible to make GitHub Actions set `fallback-version` [with each new git tag](https://stackoverflow.com/a/61892639). However `0.0.0` is most likely good enough for now.

**Comment by mraethel** [comment]
Feel free to reopen if any issues arise.
