### ISSUE TITLE
Pinentry command should probably be uppercase

### ISSUE THREAD

**Issue by otaj** [firecat53/keepmenu#149]
Hi, thank you for the library, it is awesome!

However, I was trying to use it, set `pinentry` to my very simple wrapper of `fuzzel` for `pinentry` protocol and "nothing worked" :tm:. Later on I found out, that the culprit is `pinentry` - while it is not categorically specified that commands set to to `pinentry`-like program should be uppercase, all [documentation](https://www.gnupg.org/documentation/manuals/assuan/Client-requests.html#Client-requests) seems to showcase them as uppercase, and `keepmenu` is sending everything lowercase.

I fixed my `pinentry` wrapper to accept lowercase as well, so it is solved on my end, however I think it might be correct to use uppercase.

I can send a PR with that if you want.

Thanks again for the cool little program.

**Comment by firecat53** [comment]
Fixed, thanks! Interesting that it works on some systems with lowercase (like mine).

**Comment by otaj** [comment]
Thank you very much! I think the "problem" is more my wrapper using fuzzel than regular implementations - I'd think they maybe convert everything to uppercase first, or something like that. Anyways, thank you again!
