### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by PhilT** [firecat53/keepmenu#151]
I find it a bit odd (and couldn't find an entry I thought I had to begin with) that entering search terms is case-sensitive.

If a title contains `Image-line` for example, I'd expect to be able to enter `image` and see a result.

**Comment by vaygr** [comment]
What selector are you using?

- rofi is case-insensitive by default
- dmenu, bemenu and wofi all have `-i` flag you can specify to ignore case
- don't know much about yofi

In newer utilities such as [fuzzel](https://codeberg.org/dnkl/fuzzel) this flag is added for compatibility, but is ignored since it usually doesn't make sense for such use case.

**Comment by firecat53** [comment]
I originally set the case-insensitive flag by default years ago. However, with the proliferation of various launchers, the possibility of incompatible flags between launchers, and the desire to allow people to configure their own launcher, I decided to keep as many as possible of the launcher configuration options out of keepmenu.

I'm open to suggestions for a note someplace in the README to clarify this if needed.

Thanks for the interest!

**Comment by PhilT** [comment]
Thanks both. I'm using dmenu and showing my lack of understanding of it! 

It doesn't seem to pass the options along from dwm to keepmenu. For example if I pass -b, dmenu-run will show at the bottom but if I then select keepmenu it'll be back at the top. There is a patch to enable case insensitivity in dmenu by default so I'll probably go with that.

Thanks for getting me on the right track.

Perhaps a note about how/if options are passed from keepmenu or maybe something about most options being available in the selector but honestly it's just my lack of experience with dmenu really.

I'll have another think and see if can come up with something that makes sense.

**Comment by firecat53** [comment]
It's a learning curve all right! It's been so long now, I don't even remember what I had to learn 🙂

Anytime you call dmenu, you have to pass the options to it from wherever you are calling it from. Keepmenu calls it separately from dwm, so you can't expect the options you set in your den configuration to be passed automatically to anything else.

Hopefully that makes sense! Good luck!
