### ISSUE TITLE
is there any way to use this with wmenu

### ISSUE THREAD

**Issue by treeshateorcs** [firecat53/keepmenu#157]
https://git.sr.ht/~adnano/wmenu

i have dmenu_command set as wmenu but it opens an empty prompt

**Comment by firecat53** [comment]
I added wmenu support. Checkout the dev branch and give it a try. Let me know if it all works properly!

**Comment by treeshateorcs** [comment]
okay, give me some time to figure out how to install the develop branch from AUR

**Comment by treeshateorcs** [comment]
seems to work great, thank you so much!
