### ISSUE TITLE
Ability to specify password command with parameter

### ISSUE THREAD

**Issue by varac** [firecat53/keepmenu#16]
I have stored my keepass masterpasswords in pass, and use gpg-agent.
I'd like to retrieve my passwords like this:

```
database_1 = ~/…
password_cmd = /usr/local/bin/gopass keepass-pw1
database_2 = ~/…
password_cmd = /usr/local/bin/gopass keepass-pw2
…
```

This would ease the usage of keepmenu a alot for me. Thx for this awesome app !

**Comment by firecat53** [comment]
Thanks for the kind words! Give the `develop` branch a try and see if that works for you.

**Comment by firecat53** [comment]
Hey, did you get a chance to try the develop branch to make sure what I added works for you? Thanks!

**Comment by varac** [comment]
Thx, works !!

**Comment by bwidawsk** [comment]
@firecat53 I can either re-open or start a new issue, but I'm unable to get a gpg command to work properly here. I want gpg-agent to handle this (so no pinentry). I've used the following command:
` gpg -q --for-your-eyes-only --no-tty -d ~/.mail/passwords.txt.gpg  | egrep '^keepass' | cut -d' ' -f2-`

I'm not sure how to get better error or debug messages from keepmenu...

**Comment by firecat53** [comment]
Using pipes in the command won't work because keepmenu uses `shlex.split` to parse the command into chunks, and that won't handle pipes. One way around this would be to make a small wrapper script and call that instead.

wrapper.sh

    #!/bin/sh
    gpg -q --for-your-eyes-only --no-tty -d ~/.mail/passwords.txt.gpg | egrep '^keepass' | cut -d' ' -f2-

config.ini

    ....
    passwd_cmd_1 = /home/bwidawsk/.local/bin/keepmenu_wrapper.sh
