### ISSUE TITLE
silent crash

### ISSUE THREAD

**Issue by treeshateorcs** [firecat53/keepmenu#162]
it worked flawlessly under wayland and sway wm. now that i've switched back to i3 i can't make it work. i enter `keepmenu -C` or `keepmenu -C -t` and nothing happens, it exits silently without showing me dmenu. the commented out dmenu line is what i used in sway (syntax is a bit different between wmenu and dmenu). i wish there was some kind of debug option

```ini
[dmenu]
#dmenu_command = wmenu -i -f "Iosevka Nerd Font 10"
dmenu_command = dmenu -i -fn Iosevka\ Nerd\ Font-10
pinentry = /usr/bin/pinentry-qt

[dmenu_passphrase]
nf = #222222
nb = #222222
rofi_obscure = True

[database]
database_1 = ~/Passwords.kdbx
#keyfile_1 = 
pw_cache_period_min = 10
#type_library = xdotool
autotype_default = {PASSWORD}


```

i'm using keepmenu-git from the AUR

**Comment by treeshateorcs** [comment]
omg it has solved itself!

could it be that i entered the wrong password into pinentry? i'll try that next time, so i'm not going to close this just now

**Comment by treeshateorcs** [comment]
nope. must have been some kinda glitch

**Comment by firecat53** [comment]
Glad it got sorted!
