### ISSUE TITLE
Fancy creating a release?

### ISSUE THREAD

**Issue by PhilT** [firecat53/keepmenu#167]
Hey @firecat53 , I've been running with those fixes we did for Tofi for a few months now (I see you merged them into main. Nice! Thanks). Would you create a new release and I'll update the outstanding [keepmenu PR](https://github.com/NixOS/nixpkgs/pull/328672) on NixPkgs?

**Comment by firecat53** [comment]
Done! Thanks for the reminder. I used it as an excuse to finally setup Github Actions for releasing here and to PyPi on a couple of my projects!
