### ISSUE TITLE
keepmenu --help should show help

### ISSUE THREAD

**Issue by varac** [firecat53/keepmenu#18]
`keepmenu --help ` launches dmenu, it should show the help.

**Comment by firecat53** [comment]
Added a man page instead. There are no command line options, so a man page is reasonable. Just added a note to see the man page if any arguments are passed. Check out the develop branch and see if it all makes sense to you. Thanks!

**Comment by varac** [comment]
Ok - a man page is great. I am always confused by commands not reacting on `--help` and still think even if there's no command line option `--help` would be helpful to find out. But thx for the man page anyhow.
