### ISSUE TITLE
[Feature Request] Feedback

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#20]
It would be nice to have feedback for some incorrect actions. For example, if we enter the wrong passphrase, it should give some sort of message like "Incorrect Passphrase" rather than saying nothing and immediately exiting. This should also apply when the user has incorrectly configured settings (syntax errors and what not).

**Comment by firecat53** [comment]
That's supposed to be there already. Hrm...guess I better check why it's not working!

**Comment by firecat53** [comment]
Check out the develop branch and see if the reporting is fixed/improved. Thanks!
