### ISSUE TITLE
Have option for maximum lines instead of fixed number of lines

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#21]
When specifying the number of lines with the ``` l ``` option, the menu seems to have a fixed number of lines no matter what, even when there are only 1 or 2 options to choose from (e.g. when specifying whether to manually enter or generate password or enter the passphrase). This doesn't look too good because it wastes space. It would be better if the option was changed to be a max lines option, so that the menus are only as big as they need to be, but also not exceeding a certain number.

EDIT:

OS: Arch Linux 64-bit
Kernel: 4.19 LTS
Keepmenu version: python-keepmenu-git r8.7418838-1 (AUR)

Config:
```
[dmenu]
dmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window 
l = 12

[database]
pw_cache_period_min = 5
editor = vscodium
type_library = pyuserinput
autotype_default = {PASSWORD}
database_1 = ~/main/configs/passwords.kdbx 
```
![Screenshot of asking me for the passphrase](https://user-images.githubusercontent.com/6378869/51448733-904cde00-1cf6-11e9-8a3c-bcdcba958405.png)

I tried modifying the ```lines``` parameter in my rofi config file, but didn't seem to affect the interface for my keepmenu window.

**Comment by firecat53** [comment]
I'm not seeing this behavior. I set 'l=25' in config.ini and I'm still only shown the two lines with my two database options, one line for passphrase entry, etc. If you start typing to select from a long list, the window size stays fixed, but that's just a function of dmenu.

You'll have to provide screenshots and config file along with system specs and version of keepmenu being used.

**Comment by starun96** [comment]
Updated the original post with the relevant info.

**Comment by firecat53** [comment]
Made a small change that should work. Try the develop branch and see if that works for your same configuration. This was the originally intended behavior but apparently I missed it!
