### ISSUE TITLE
Add "create database" feature

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#22]
I really like keepmenu because it does pretty much everything I want with my KeePass database. However, the only thing that keeps me from using it as my sole KeePass desktop client is the fact that it cannot create or manage databases (to my knowledge). For example, if the database file specified in the config file doesn't exist, then keepmenu should prompt you to create it and insert the relevant info (master password, etc.). I would like for there to be some way to create and manage databases so I can use this as my sole desktop client for KeePass.

**Comment by firecat53** [comment]
Unable to do so until this is added in pykeepass. It's already tracked there: https://github.com/pschmitt/pykeepass/issues/8

Looks like someone just needs to implement it :smile:

**Comment by Evidlo** [comment]
It is done

**Comment by starun96** [comment]
Thank you!

**Comment by firecat53** [comment]
It's implemented in pykeepass...awaiting implementation in keepmenu.
