### ISSUE TITLE
Can't use notes field

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#23]
For some reason, whenever I try to edit the notes field of a particular entry, not only does the editor (which I chose as ```gui_editor = vscodium ```) not show up, but keepmenu exits and doesn't come back until after I reboot my machine. I keep trying to invoke keepmenu via a keybinding, but it refuses to show up. I typed "keepmenu" in the terminal it seems to immediately terminate without showing any output. I tried to kill the keepmenu daemon via ```pkill keepmenu```, which had no effect, which means it probably stopped running. I even tried tried uninstalling and then reinstalling keepmenu, but I still can't open it. Again, it took a reboot to get it to start working again. This is rather frustrating, and I hope that this bug can be fixed.

System: Arch Linux, Linux Version: 4.19 LTS, using i3 Window Manager
Invoking keepmenu by: Using i3 keybinding (alt+shift+space)

Keepmenu Config:
```
[dmenu]
dmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window 
l = 12

[database]
pw_cache_period_min = 5
gui_editor = vscodium
type_library = pyuserinput
autotype_default = {PASSWORD}
database_1 = ~/main/configs/passwords.kdbx
```

**Comment by firecat53** [comment]
I'm not at my computer right now, but if you can first check that `gui_editor = gvim` works (with gvim installed of course). I'll poke at some later.

**Comment by firecat53** [comment]
Give the develop branch a try if you can. Turned out to be a simple fix. However, you will need to use `gui_editor = vscodium -w` to ensure vscodium will work properly to return the value from the editor. Similar to how you would need to use `gvim -f`.
