### ISSUE TITLE
Autotype doesn't work about a quarter of the time

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#24]
When using Qutebrowser, I noticed that autotyping my password failed about a fourth of the time; Sometimes the password had most of its characters turned uppercase, while also turning characters such as 2 into @ and 0 into ). For example: 2example43 -> @EXAMPLe43. It seems like the autotyping mechanism thinks that the Shift key is held down or the CAPS lock is on, even though it actually isn't when I am autotyping it. Interestingly enough, this is only a problem inside Qutebrowser.

However, I also noticed that when I *did* have CAPS lock on or held down the Shift key, the same result occurred everywhere.

I'm wondering if there is a fix for this problem or perhaps maybe there is something wrong with Qutebrowser in how it somehow thinks that the Shift key is down or the CAPS lock key is on.

System: Arch Linux, Linux Version: 4.19 LTS, using i3 Window Manager and Qutebrowser
Invoking keepmenu by: Using i3 keybinding (alt+shift+space)

Keepmenu Config:

[dmenu]
dmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window 
l = 12

[database]
pw_cache_period_min = 5
gui_editor = vscodium
type_library = pyuserinput
autotype_default = {PASSWORD}
database_1 = ~/main/configs/passwords.kdbx

**Comment by firecat53** [comment]
Yep, I've noticed this as well from time to time. Try switching to xdotool and see if that makes any difference. It may be something to do with pyuserinput.

**Comment by starun96** [comment]
Unfortunately, switching to xdotool didn't do anything. I'm going to try to experiment with the Insert Mode in Qutebrowser and see if I can solve the issue that way.

**Comment by firecat53** [comment]
I'll go ahead and close this. Sounds like if people have trouble with pyuserinput, xdotool seems to work ok.
