### ISSUE TITLE
Have inactive timeout instead of just fixed timeout

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#26]
I think it would be really helpful if keepmenu would remember the password for a period of time after last accessing keepmenu rather than a fixed amount of time as it is right now. I find myself running into situations where I am constantly using keepmenu in a 5 min period only to find myself faced with another master password prompt even though I was using it a second ago. This breaks my concentration. I could just increase the cache time period right now, but I don't think that's ideal.

For example:
`inactive_timeout=1`
If it's been 1 minute since you last accessed keepmenu, then ask for the master password again.

**Comment by firecat53** [comment]
Sounds like a reasonable request. I'll see what I can do. I'll probably switch it so it always uses the inactive timeout instead of a fixed timer. That seems to make more sense!

**Comment by firecat53** [comment]
Made this change in the develop branch. Let me know if it works as you expect. It should reset the timer anytime keepmenu is opened.
