### ISSUE TITLE
'future' module not found

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#28]
Recently when I was using keepmenu, I noticed that it just refused to start. When I ran `keepmenu` directly in my terminal, it said:

```Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 26, in <module>
    from pykeepass import PyKeePass
  File "/usr/lib/python3.7/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 8, in <module>
    from future.utils import python_2_unicode_compatible
ModuleNotFoundError: No module named 'future'
```

I have no idea why this happened. I can only guess that I updated my Arch system via `sudo pacman -Syu` and that might have updated PyKeepass in some way? I updated my system again via `yay -Syu` (for the AUR), but that didn't seem to update keepmenu. In any case, I found the solution already: I just need to install the `future` package via `pip3 install --user future`. However, I am concerned that I had to go out of my way to install something just so keepmenu wouldn't break. I would imagine Arch's package manager would have managed the dependencies for me.

I just wanted to let you know. Perhaps this dependency issue can be worked out?

**Comment by firecat53** [comment]
Thanks. I submitted an [Arch bug report](https://bugs.archlinux.org/task/61968?project=5&order=dateopened&sort=desc). Just a packaging issue with python-pykeepass.

**Comment by starun96** [comment]
Thanks! I really appreciate the work you've done!
