### ISSUE TITLE
Keepmenu crashes after entering Autotype sequence

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#31]
After specifying an Autotype sequence for a particular entry (`{PASSWORD}`), keepmenu just crashed. I wasn't able to relaunch it either by calling `keepmenu` in the terminal. I was only able to use keepmenu again after logging out and logging back in. **(EDIT: I have to reboot my computer entirely, actually)** This happens every time I try to change the autotype sequence for an entry. This is very similar to issue #23. 

System: Arch Linux (Linux LTS: 4.19.31-1)
Window Manager: i3-gaps
Config:

```
[dmenu]
dmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window 
l = 12

[database]
pw_cache_period_min = 5
gui_editor = vscodium --extensions-dir ~/main/configs/vscode/extensions -w
type_library = xdotool
autotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}
database_1 = ~/main/configs/passwords.kdbx
```

**Comment by firecat53** [comment]
I think I'll add some logging that can be activated with a command line switch. You can start keepmenu from the command line and then when an error happens, you should be able to see the traceback.

In the meantime, you should be able to kill the crashed process with `killall keepmenu` so you don't have to relogin each time that happens!

I can reproduce this here, so I'll dig into it when I can! Thanks for the report.

**Comment by starun96** [comment]
The thing is, I've already tried to kill keepmenu via `pkill keepmenu` and `killall keepmenu`. The next time I tried to launch it, it wouldn't start up. And recently I've realized that it's not merely logging in or logging out that solves the problem, but rather rebooting my machine entirely. I have no idea why that's the case, but it just is.

**Comment by firecat53** [comment]
That's very odd. How are you starting it?

**Comment by starun96** [comment]
In my i3 config, I have bound shift+mod4+space to launch keepmenu (`bindsym $mod+shift+space exec keepmenu`). 

The output of `ps aux | grep keepmenu` is 

```
user     5680  5.0  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5691  0.3  0.5 324344 33544 ?        Sl   04:14   0:00 python /usr/bin/keepmenu
user     5692  0.0  0.5 324344 31540 ?        Sl   04:14   0:00 python /usr/bin/keepmenu
user     5711  0.0  0.0   6580  2264 pts/0    S+   04:15   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu

```

After trying to edit the autotype sequence of a particular entry, `ps aux | grep keepmenu` gets me:

```
user     5680  0.3  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5692  0.0  0.5 389880 34604 ?        Sl   04:14   0:00 python /usr/bin/keepmenu
user     5881  0.0  0.0   6580  2224 pts/0    S+   04:18   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu
```

After trying to run keepmenu again (in the terminal), I get this:

```
user     5680  0.3  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu
user     5692  0.0  0.5 389880 34608 ?        Sl   04:14   0:00 python /usr/bin/keepmenu
user     5907  0.0  0.0   6580  2324 pts/0    S+   04:19   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu
```

**Comment by starun96** [comment]
Hi, has there been any progress made on this issue? Thanks.

**Comment by firecat53** [comment]
No, I haven't had time to sit down and work on it yet.

**Comment by firecat53** [comment]
This is actually a pykeepass issue when opening entries that have been brought forward from an older database. It doesn't automatically create the 'autotype_sequence' field when editing, which generates the error we are seeing.

Workaround: export your database as a CSV from KeepassXC. Import the CSV into a new database using KeepassXC . This fixes the problem for me.

As for having to reboot when keepmenu crashes: I have no idea. To me, this sounds like a problem with your system. Not being able to kill a process using `killall` or `kill -9` just isn't right! :)

**Comment by firecat53** [comment]
Was this ever resolved for you?

**Comment by firecat53** [comment]
Please reopen if this is still an issue. Thanks!
