### ISSUE TITLE
Obscure password entry in 'Edit Entries' mode?

### ISSUE THREAD

**Issue by aclindsa** [firecat53/keepmenu#33]
How hard is it to add a feature to obscure the password for an entry when you go into 'Edit Entries' mode so it's not visible by default? For instance, if you were forced to navigate to the Password entry itself and hit Enter to be able to view it. Perhaps this could be a config option if folks wouldn't want that behavior by default?

**Comment by firecat53** [comment]
Give the develop branch a try. I went ahead and changed to a hidden password by default, but ask for password confirmation when entering one manually. Added notes to README and man page.

**Comment by aclindsa** [comment]
@firecat53 Awesome, thanks! I gave it a shot, and think this looks good. It allows me to edit information without my password being immediately displayed.

My only thought is that some folks might like to still have a menu option under the 'Password' menu that will display the current password. After playing around, I understand that selecting 'Manually enter password' will allow you to do that since the default selection there is the current password, but I suspect that's not the intention of that menu item, and isn't immediately obvious.

**Comment by aclindsa** [comment]
Heh, after commenting, I now see that you've already added how to use 'Manually enter password' to display the password to the documentation. I think that's a fair compromise if you prefer not adding a separate menu entry for it.
