### ISSUE TITLE
Editing empty passwords

### ISSUE THREAD

**Issue by aclindsa** [firecat53/keepmenu#36]
It seems like when I attempt to edit empty passwords (i.e. the entry has already been created, but is empty), keepmenu crashes. I looked at the code in edit_entry, but I don't think I understand why 

```
if field == 'password':
    sel = kp_entry.password
```
is above 
```
edit_b = sel.encode(ENC) + b"\n"
```
... so I'm creating this issue instead!

The `sel.encode(ENC)` is the line it's crashing on because `sel` is `None`.

**Comment by firecat53** [comment]
Give the development branch a try. Easy fix, I hope!

Thanks so much for being patient and submitting bug reports!!

**Comment by aclindsa** [comment]
That appears to have fixed the issue for me, thanks!
