### ISSUE TITLE
keepmenu crashing

### ISSUE THREAD

**Issue by cj360** [firecat53/keepmenu#4]
Am I missing a python  package?
Installed from aur

```$ keepmenu 
Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 937, in <module>
    MANAGER = client()
  File "/usr/bin/keepmenu", line 755, in client
    mgr.connect()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 941, in <module>
    run()
  File "/usr/bin/keepmenu", line 926, in run
    dmenu = DmenuRunner(server)
  File "/usr/bin/keepmenu", line 768, in __init__
    self.database = get_database()
  File "/usr/bin/keepmenu", line 280, in get_database
    db_l[-1] = get_passphrase()
  File "/usr/bin/keepmenu", line 344, in get_passphrase
    password = dmenu_cmd(0, "Passphrase")
  File "/usr/bin/keepmenu", line 220, in dmenu_cmd
    extras = (["-" + str(k), str(v)] for (k, v) in args_dict.items())
UnboundLocalError: local variable 'args_dict' referenced before assignment```

**Comment by firecat53** [comment]
- Did you start with a config.ini or let keepmenu generate it on first run?
- Either way, can you please post the config.ini that you are using.

Thanks!

**Comment by cj360** [comment]
Installed a day or two ago and let keepmenu create the config, then edited in location of my database.
config.ini:  http://ix.io/XrQ

**Comment by firecat53** [comment]
I think I see where the bug is... hopefully I'll have it fixed today! Thanks for the report!

**Comment by firecat53** [comment]
Oh, and in the meantime, just add a section `[dmenu]` to your config.ini.

**Comment by cj360** [comment]
Oh yeah forgot to mention I was intending to try this with rofi, should I have [dmenu] or [rofi] in my config depending on which one I want to use?

**Comment by firecat53** [comment]
No, just the `[dmenu]` section with ` dmenu_command = rofi`.

**Comment by cj360** [comment]
Updated config to: http://ix.io/XuR

keepmenu says invalid pw, even though said pw is correct and works with keepass(mono based v.program).

**Comment by firecat53** [comment]
Hrm. That's tougher to troubleshoot from here...

* doublecheck your keyfile is spelled correctly in config.ini
* Try adding your passphrase to config.ini and see if that works
* Any non-US or funky characters in the password?

If you still have trouble, we could chat on IRC and see if we can solve it real time.

**Comment by firecat53** [comment]
Any chance you can test the develop branch for me before I push to master? Pretty sure I squashed the initial bug you reported.  If you're not comfortable with that, no worries.

Also let me know if you get it working with your password/keyfile.

Thanks for your patience!

**Comment by cj360** [comment]
Starting to wonder if it is something in my database causing an error...
http://ix.io/XC0

config: http://ix.io/XC3
doesn't include actual pw but its just english letters & numbers

**Comment by firecat53** [comment]
Ah, yes...I saw that before and thought I fixed it so it wouldn't error out on bad characters in the database. Standby...

**Comment by firecat53** [comment]
Are you using python 2 or 3? Any chance you can troll through your database and see if you can find an odd character someplace and maybe create a new database using keepass just with a one fake entry containing that character? If the database is too large, I understand and I'll see what I can do.

**Comment by firecat53** [comment]
You must be using python2. I made a entry with that character é and it's erroring out. Works fine with python3. Sigh. It's tempting to drop support for 2, but I'll see if I can work around it. Unicode support is horrible...

**Comment by cj360** [comment]
Should be using 3 as thats the default on Arch.

**Comment by firecat53** [comment]
You might wanna check that...I'm almost positive that you're using python2 to run keepmenu because of the error. I get the _exact_ error that you did when I run it using python2!

**Comment by firecat53** [comment]
That's very odd...not normally an error message you see when using python 3. Anyway...sounds like you've got access to your database now that you've sorted the error?  I'll still try and make it more robust so at least it won't crash on a bad character.

Any other issues you've found yet? I really appreciate the feedback!

**Comment by firecat53** [comment]
I pushed a fix to the develop branch for Unicode characters in the database that should fix any issues with Python 2. Hopefully this fixes the last of your keepmenu issues for now!
