### ISSUE TITLE
Error: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by starun96** [firecat53/keepmenu#42]
System: Arch Linux 4.19 LTS

Every time I try to open keepmenu (edit: after typing in my database password), I get the error message stating 'bytes' object has no attribute 'encode'. This happened after I recently updated my version of keepmenu to the latest version (r97.6634843-1 from AUR). I haven't updated in quite some time. Not quite sure what is causing this issue.

I have already tried uninstalling it and then reinstalling it via pip. (`pip3 install --user keepmenu`). Then I edited the config file to change the database path to my database. I had the exact same error with that config.

**Comment by firecat53** [comment]
Can you please post the actual traceback? I can't tell where the error is coming from otherwise.

**Comment by starun96** [comment]
As far as I know, there is no traceback that I have seen. When I run keepmenu in the terminal, the only thing that is outputted in it is "xdotool version 3.20160805.1". After that, once I get the "byte object has no attribute encode" error message in the rofi menu itself and press Enter, the program terminates and nothing else is shown in the terminal. I am also not aware of any debug mode.

**Comment by firecat53** [comment]
Ok... I'm gonna be gone until next week. If you find anything else let me know. I've been meaning and failing to add logging for some time now.

If you have time, create a new database with KeepassXC and see if keepmenu can open it. I'm running the same OS you are so that's the only thing off the top of my head that I can think might be different... the database.

Also check that the supporting libraries are up to date and you don't have any old versions installed to ~/.local/share that are overriding the system installed libraries.

**Comment by starun96** [comment]
I created a new db with the password "some_simple_password" and successfully opened it through keepmenu. However, my old db password didn't have special characters; only alphanumeric ones, so I don't see how this helps much. So I guess maybe there's something wrong with my existing database? Though other KeePass clients can open it just fine.

**Comment by firecat53** [comment]
[This error](https://github.com/firecat53/keepmenu/issues/27) I think was similar. They were able to 'fix' it by exporting and then reimporting their database into Keepass. I still don't know why...maybe a pykeepass error somehow? Even if that works for you, leave this open so I'll remember to add logging...

**Comment by starun96** [comment]
Yep, that did the trick.

I just used keeweb to export my database as XML. Then I used keeweb again to reimport that XML into a new database with the same password. I then made my keepmenu config and phone's KeePass client point to the new db location. I'll let you know if there are further issues.

**Comment by firecat53** [comment]
Awesome! Thanks for your patience.

**Comment by firecat53** [comment]
Seems to be resolved for everyone here, so I'll close. Thanks!
