### ISSUE TITLE
Typing field individually types entry twice

### ISSUE THREAD

**Issue by scrblue** [firecat53/keepmenu#47]
Going into the View/Type Individual entries menu and selecting an entry's username or password autotypes the field twice.

**Comment by firecat53** [comment]
I believe that was fixed with eb1f661c a couple of months ago. Try updating your installed version.

**Comment by scrblue** [comment]
I'm on 0.5.8 which is the latest release on pip.

**Comment by firecat53** [comment]
Yep...that fix was put in place after the 0.5.8 release to Pypi. Until I can release a new version you can download the project, cd to the directory, then `pip install --user -e .` Thanks for your patience!

**Comment by firecat53** [comment]
Version 0.6.0 released on Pypi.
