### ISSUE TITLE
Fine-grained control over password generation

### ISSUE THREAD

**Issue by das-s** [firecat53/keepmenu#51]
Hey all, 

is there interest for a more fine-grained control over the password generation? 

On some sites, especially non-english ones, there are specific requirements for the special characters used in the password. The current [implementation](https://github.com/firecat53/keepmenu/blob/master/keepmenu#L56) only allows to pick all or none.

I think it would be preferable to be able to set those via the config file or even in rofi/dmenu. I'd help with the implementation as well if my python skills are up to the task.

**Comment by firecat53** [comment]
Sorry for the delayed response. That sounds like a reasonable idea. I also struggle with those really dumb special character restrictions :roll_eyes:

**Comment by das-s** [comment]
How would you go about implementing this? Should this be manageable via the rofi/dmenu interface or only via the config file? KeepassXC uses an interface like this:
![2020-04-05_15-04](https://user-images.githubusercontent.com/47145187/78499112-4eaf2400-773e-11ea-9505-c6eff653ad8e.png)

The easiest implementation would probably be to be able to overwrite the `string.punctuation` with a custom string from the config.

However, defining sets made of custom groups and having those sets of character combinations inside rofi would be very convenient. For example, having set1 with letters, digits, brackets and set2 with all of these plus punctuation symbols configured in the config. One would then select `set1` or `set2` during password generation in rofi/dmenu. This could subset the current selection process for digits and special characters. Thoughts?

**Comment by firecat53** [comment]
Yep, I think defining as many sets as desired in the config would be the cleanest way to implement this.

**Comment by das-s** [comment]
I'll look into it.

**Comment by firecat53** [comment]
Closed by #52, b6da92330.
