### ISSUE TITLE
[request] Update AUR package

### ISSUE THREAD

**Issue by marcosrdac** [firecat53/keepmenu#53]
There was a problem you solved last year, about entries being typed twice. I would like to have it solved also when I install the package from AUR. Could you please make an update there when you get some time?

Already thankful!

**Comment by firecat53** [comment]
The AUR package is a -git package and will always install the latest master from GitHub. You just need to reinstall/update the python-keepmenu-git package. Hopefully that answers your question!

**Comment by marcosrdac** [comment]
Wow, that was fast! I've just done it, and you were right (I'm feeling very dumb now hahaha)

Thanks a lot :)
