### ISSUE TITLE
autotype confuses "_" and "—"

### ISSUE THREAD

**Issue by br-olf** [firecat53/keepmenu#55]
I'm new to i3 so maybe this is just a configuration problem. If so, sorry for cluttering the bugtracker.

When I'm performing an autotype with keepmenu any "_" is replaced with "—" and I'm unable to login.

I'm using arch and have installed keepmenu from AUR.

In my i3 config I set my keymap to neo using:
```
exec setxkbmap de neo
```

Furthermore I'm using `dmenu_command = /usr/bin/rofi` in the config.ini

**Comment by firecat53** [comment]
Try using xdotool for the `type_library` (see README and config.ini.example).

    [database]
    type_library = xdotool

It's necessary when you have a non-English keyboard layout

**Comment by hasufell** [comment]
Why is xdotool not standard? non-English layouts are likely a significant amount.

**Comment by firecat53** [comment]
Because it's not automatically installed along with Python and not part of the Python ecosystem. It's an easy install for those that need it.

Did xdotool fix your issue?

**Comment by hasufell** [comment]
> Because it's not automatically installed along with Python and not part of the Python ecosystem. It's an easy install for those that need it.

Yes, but not compelling arguments, IMO. A tool messing up special chars in passwords has a slightly unprofessional taste to it, even if it's not the fault of your code. So, I personally would rather have users install it instead of relying on that python lib, which clearly does not work well.

> Did xdotool fix your issue?

Yes, but it took quite a while to figure out what the issue was.

**Comment by firecat53** [comment]
I see your point and I will think about it. Thanks for the feedback!

**Comment by br-olf** [comment]
> [database]
> type_library = xdotool

Sry, for my late reply. 
This fixed my issue. Thanks a lot.

Regarding the suggestion of @hasufell:
TBH I didn't read the config.ini very carefully but a hint regarding this in the README would have prevented me from asking ;)

**Comment by firecat53** [comment]
5. under the requirements in the README says that xdotool is required for non US keyboard layouts. I'll move that up a bit and remove the 'optional' label since it really isn't for a lot of people!
