### ISSUE TITLE
Passwords are often miscopied

### ISSUE THREAD

**Issue by hasufell** [firecat53/keepmenu#59]
I often have to repeat the process:

1. open keepmenu
2. select "View/Type Individual Entries"
3. select my gpg key
4. have it copied incorrectly (the first char ends up uppercase, although it isn't)

`type_library = xdotool` is set.

This also lead to bigger problems where I copied a passphrase into terminal, where I cannot see whether it was copied correctly and then had a private key I could not recover at that time.

I'd expect a password manager to be able to copy my passwords correctly.

**Comment by firecat53** [comment]
Yeah, unfortunately I occasionally have that issue too, although not too often. I think it's a problem with the typing library xdotool or PyUserInput, or perhaps how I'm calling them. At some point I'll switch to pynput (#54) and hopefully that will help. I'm open to other ideas on how to troubleshoot, as it appears to be somewhat random :frowning_face: It does feel like sometimes when I'm trying to open keepmenu and type too fast is when the problem occurs...perhaps some unwanted keystrokes get inadvertently typed?

**Comment by The-Compiler** [comment]
I started using keepmenu yesterday and see this some 30% of the time - it does seem to be connected with the shift key somehow not being registered - for example, I've observed an email being auto-typed as `username2domain` instead of `username@domain` (with an US keyboard layout, so `@` is `Shift+2`).

This is without `type_library` set, but I'll try with `type_library = xdotool` now and see if that helps in any way.

**Comment by firecat53** [comment]
I was also going to try adding in a slight delay between letters, similar to the delay when Keepass or KeepassXC type passwords, and see if that helps (in addition to the pynput switch).

**Comment by firecat53** [comment]
Tried with pynput and it seems to be working fine for the most part. It will occasionally capitalize the first letter of the username though.

**Comment by firecat53** [comment]
@hasufell, have you noticed any improvement using pynput, or any problems when using xdotool?

**Comment by PRESFIL** [comment]
@firecat53, for me, on the contrary, `xdotool` works. `pynput` out of the box - not.

**Comment by The-Compiler** [comment]
I've also still noticed issues with Pynput, where apparently typing capital letters with Shift doesn't always work :worried: Trying `xdotool` now.

**Comment by firecat53** [comment]
Has anyone noticed this issue recently? I've been using either xdotool, ydotool, or wtype for keepmenu and [bitwarden-menu](https://github.com/firecat53/bitwarden-menu) for quite some time now with any problems.

**Comment by firecat53** [comment]
Closing. I haven't seen this issue for quite awhile and have received no other recent reports.
