### ISSUE TITLE
Autotype setting from KeePass

### ISSUE THREAD

**Issue by AichP** [firecat53/keepmenu#6]
Hey, cool stuff.
First Question, am I missing something or is the default autotype behaviour always username tab password? Set Autotype sequence from within KeePass doesn't seem to have an effect.

**Comment by AichP** [comment]
Ah I see, I guess its not worth the effort. The problem only occurs when an Enter is needed in between the username and the password. The command line would be one example.
Guess its easier to just have the entry duplicated with only the password. Not a big deal at all.

**Comment by firecat53** [comment]
Don't forget you can also just use the View/Type entry option to only type the username or password for an entry instead of creating a duplicate entry.

**Comment by AichP** [comment]
Ahh! Well, again cool stuff! :smiley: 
Thx
