### ISSUE TITLE
Writing empty note crashes the application

### ISSUE THREAD

**Issue by Riyyi** [firecat53/keepmenu#60]
I attempted to remove a note, so I cleared all the text in the temporary file, but after quitting out of the editor keepmenu wont start anymore and the change isnt saved. I have to manually kill the python processes before it starts again. I tested it with GUI Emacs and Vim.

**Comment by firecat53** [comment]
Hmm, I can't replicate that here with either Vim or EMACS. What version of keepmenu are you using? Can you post your config (uncommented lines only)?

**Comment by Riyyi** [comment]
Woops, I'm using pyhon-keepmenu-git from the Arch AUR, so I was running a very old version.
```sh
$ pacman -Qs keepmenu
local/python-keepmenu-git r89.ddc7262-1
    Dmenu/Rofi frontend for Keepass databases.
```
Apparently it doesnt update git packages unless the PKGBUILD is updated, I've never encountered this issue before.
Thanks for the quick response, it works fine on the latest commit!
