### ISSUE TITLE
Keepass field references

### ISSUE THREAD

**Issue by elmir-b** [firecat53/keepmenu#75]
Keepass allows field references in usernames and passwords. From https://keepass.info/help/base/fieldrefs.html

`KeePass can insert data stored in different entries into fields of an entry. This means that multiple entries can share a common field (user name, password, ...), and by changing the actual data entry, all other entries will also use the new value.`

keepmenu copies the reference text and NOT the actual reference value.

**Comment by elmir-b** [comment]
@firecat53 I have actually fixed this and prepared a PR, but I cannot push a new branch, can you give me the proper access rights?

**Comment by firecat53** [comment]
You don't need access to this repo to submit a PR. You create the branch in your own fork and base the PR on that branch.

Thanks for the interest!

Feb 25, 2021 06:08:41 Elmir B <notifications@github.com>:

**Comment by elmir-b** [comment]
@firecat53 done, thanks. My first contribution to a project not owned by me or organization I belong to so I was unaware of this

PR is created and linked.
