### ISSUE TITLE
Keepmenu crashing as low-priv user - Connection refused

### ISSUE THREAD

**Issue by 0x5c4r3** [firecat53/keepmenu#77]
I run keepmenu in Arch, nothing really special.
It's been a while since I keep getting this error without figuring out why.
I am sure I am missing something stupid, but I cannot understand what's that I am missing.
I start keepmenu as user, input the password and the dmenu opens correctly, showing the list of entries.

**Strange things:**

1) instead of showing the normal list of entries like:
`0 - entry_0  -  username_example  -  URL_example` 
`1 - entry_1  -  username_example  -  URL_example` 
`2 - entry_2  -  username_example  -  URL_example` 
it shows the titles like so: 
`0 - [ 'entry_0' ]  -  username_example  -  URL_example` 
`1 - [ 'entry_1' ]  -  username_example  -  URL_example` 
`2 - [ 'entry_2' ]  -  username_example  -  URL_example` 

2) if I try to paste the whole user and password row (without going into _View/Type Individual Entries_) it does copy the user and pass, while if I try to copy single items like the single password of a row (so going into _View/Type Individual Entries_ ) it does not copy anything and crashes, reporting this error:

![2021-03-05_12-44](https://user-images.githubusercontent.com/16732213/110117205-74aad180-7db0-11eb-80f1-b0bfe04f2e9c.png)

3) If I do the same process as root user, everything works perfectly. db opens and work as expected.

**Attempts I did to fix the thing:**

1) I changed database and I get the same error, so I don't think it's an issue related to the db (yes, I do use .kdbx). Every db I tested is opening and working properly in keepass.

2) I changed permissions to the DB, nothing changes, same exact problems.

3) tried to install keepmenu from different sources, git, aur, pip. Same problems.

If you need, here's the config file (the keyfile row is commented since I am not using any keyfile atm):

![image](https://user-images.githubusercontent.com/16732213/110119328-935e9780-7db3-11eb-9248-d507227b4fce.png)

Again, I am 100% sure that probably I am missing something stupid, but I cannot understand what.

**Comment by firecat53** [comment]
What version of python-pykeepass do you have (current community version is 3.2.1)? Check in `~/.local/lib/python3.9/site-packages` to make sure you don't have an old version being used.

If that seems normal, can you send me a small sample kdbx file that exhibits the problem?

**Comment by 0x5c4r3** [comment]
so, this is the content of `~/.local/lib/python3.9/site-packages`:

![image](https://user-images.githubusercontent.com/16732213/110221837-520adc80-7ec6-11eb-8bdb-621d85c5a6aa.png)

I tried both AUR release and pip release and they both have the same problem, 
But thinking about Keepmenu working perfectly as root, it probably means that I installed something wrong in the user's .local/bin folder.

Do you see anything wrong that could cause the issue?

About the .kdbx, I am also sure that that should not be the problem since playing with other databases, I discovered that they all have the same issue.

**Comment by firecat53** [comment]
Delete pykeepass* from that directory. Install python-pykeepass via pacman.

**Comment by 0x5c4r3** [comment]
Problem solved, thank you so much for your super fast replies!

**Comment by firecat53** [comment]
I discovered this morning that Arch is still using pykeepass 3.2.1, which is why it's working. The latest pykeepass 4.0.0 which you probably installed initially from pip is what is causing the display of lists instead of strings. I don't know when the Arch package will be updated. Hopefully I'll have a fix in place soon

**Comment by 0x5c4r3** [comment]
That's interesting! Btw thanks a lot for your work, I'm really in love with
keepmenu.
Good Job!

Mat

**Comment by 0x5c4r3** [comment]
Hey @firecat53, just wanted you to know that seems like Arch is now using pykeepass 4.0.0, I just updated the system this morning and I am unfortunately getting the same error as before..

**Comment by firecat53** [comment]
Pretty sure you've some locally installed vs system install conflicts. Go into `$HOME/.local/lib/python3.9/site-packages` and `$HOME/.local/bin/` and delete all references to keepmenu, pykeepass and pynput. Then install keepmenu again from the AUR.

**Comment by 0x5c4r3** [comment]
ok probably I got the mistake, using i3, I had keepmenu configured to run the `/home/USER/.local/bin/keepmenu` binary instead of `/usr/bin/keepmenu`. Let's see, for now it's working, I guess if it will have problems once I will update the system (I guess not, since I did as you told me and I deleted all references related to keepmenu | pykeepass | pynput).

**Comment by firecat53** [comment]
It actually wasn't your mistake. There is a legitimate packaging error with the python-pykeepass that messed you up and will probably mess other people up until it gets fixed! It's most likely working because you have a local user version of pykeepass 4.0.0 still installed.
