### ISSUE TITLE
Feature Request: Integrate the use of TOTPs

### ISSUE THREAD

**Issue by ghillb** [firecat53/keepmenu#86]
First of all, keepmenu works great and I love it!

Is there any chance of getting TOTP support like KeePassXC has?

I would love to use keepmenu as TOTP filler via the {TOTP} autotype sequence. Seems like a natural fit.

> {TOTP} | Insert calculated TOTP value (if configured)
- https://keepassxc.org/docs/KeePassXC_UserGuide.html

**Comment by firecat53** [comment]
In progress! See PR #87

**Comment by firecat53** [comment]
TOTP support added thanks to @anguye21!
