### ISSUE TITLE
Feature: Add CLI options for databases

### ISSUE THREAD

**Issue by dylantjb** [firecat53/keepmenu#91]
I manage multiple databases that I access with keepmenu via a keyboard shortcut. While using the 'Open another database' dialog is functional, after multiple uses a lot of time is wasted typing, and it's confusing to know what database you are on when it loads from cache.

Using keepmenu with a CLI option for the database you want would be helpful as I could set multiple shortcuts to distinguish them.

**Comment by firecat53** [comment]
Would including the database path in the title on the first page make it easier to see which database?

I only ask that because it's a much quicker solution to implement than CLI flags 😀

**Comment by dylantjb** [comment]
It would help a lot, although the 'Open another database' dialog issue remains. I frequently switch from my passwords database to my TOTP database to enter information and the time to switch really builds up.

I was thinking it could input the argument and bypass the "Select Database" prompt if it used. The databases would already be configured in config.ini, but the user could specify one with something like '--database 2'.

**Comment by firecat53** [comment]
I'd probably use an absolute path and also include a path to keyfile option.

Out of curiosity will you be taking advantage of the new TOTP feature I merged yesterday? If so, I'd love some feedback on usability and usefulness!

**Comment by dylantjb** [comment]
I agree, just thought it would be the easiest to add.

I've been using the totp branch in the pull request for a long time now and I think it works pretty well. Adding/editing is seamless and so is the autofill, but for my particular case I had a small issue with it. Now that it's been merged I've added an issue here #92.
