### ISSUE TITLE
keepmenu crashing from source/AUR

### ISSUE THREAD

**Issue by tenklo** [firecat53/keepmenu#96]
I've been using keepmenu for a while, thank you for your hard work!

Previously I installed keepmenu via pip on arch linux, which worked fine.
Since the version which gets installed via pip is tag 1.0.0, which does not have the otp functionality, I wanted to get to the new feature by other means.

But either cloning the repo or installing from the AUR leaves me with following error message:

    Traceback (most recent call last):
      File "/usr/bin/keepmenu", line 1849, in <module>
        conn = MANAGER.get_pipe()  # pylint: disable=no-member
      File "/usr/lib/python3.9/multiprocessing/managers.py", line 715, in temp
        token, exp = self._create(typeid, *args, **kwds)
      File "/usr/lib/python3.9/multiprocessing/managers.py", line 600, in _create
        id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
      File "/usr/lib/python3.9/multiprocessing/managers.py", line 93, in dispatch
        raise convert_to_error(kind, result)
    multiprocessing.managers.RemoteError:
    ---------------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3.9/multiprocessing/managers.py", line 212, in handle_request
        result = func(c, *args, **kwds)
      File "/usr/lib/python3.9/multiprocessing/managers.py", line 371, in create
        self.registry[typeid]
    KeyError: 'get_pipe'

I'd really love to get this working, any ideas?

Edit:
When switching to 1.0.0 in the clone things also work without errors. Main and develop do not work.

**Comment by tenklo** [comment]
Thank you for your reply!

`keepmenu -h` does work and outputs the usage message.
Running `keepmenu` on its own still gives that same error.
It is the same when running via a virtualenv.

So it seemed it worked while not having to call dmenu... maybe?

This reminded me of the issues I had when trying keepmenu for the first time:
I use my own dmenu with patches, one of which removed the "-i" option. I had to readd that option as a dummy (
```
else if (!strcmp(argv[i], "-i"))   /* do nothing, keepmenu compatability */
			;
```
) in dmenu.c to make keepmenu work the last time.

But also with vanilla dmenu, installed via `sudo pacman -S dmenu`, I get the same error.

I don't believe I did install anything via `sudo pip install`; is there an easy way to check?
Still, tag 1.0.0 works fine...

**Comment by firecat53** [comment]
Are you using any non-standard python (pypy, cpython, etc)?

It may be impossible for you, but if can, try uninstalling as many of your
system python modules as possible and if you need to keep some installed, make
sure that the entries in /usr/lib/python/site-packages match what you expect to
be installed.

Also, (again, if possible without breaking your system) try deleting everything
in ~/.local/lib/python3.9/site-packages and reinstalling your keepmenu
requirements `pip install --user -r requirements.txt`. This should have been a
non-issue when you tried keepmenu in a virtualenv though. That's why I'm more
suspecting something weird at the system level.

If you can, try spinning up a fresh Arch machine in Virtualbox or libvirt and
see if you can replicate the issue.

**Comment by tenklo** [comment]
@firecat53 
I am using standard Python 3.9.7.

As I'm not really sure which packages are important and removing them one by one would take a while (a lot have accumulated apparently), so I wont try that for now.

I did try keepmenu on another hardware machine tho, with the same result. But they are set up very similarly, so the same system issue might be there too.

Using pyenv wouldn't be much different from trying the virtualenv in this case, would it?

@anguye21 
Thank you for your suggestion!
`pgrep keepmenu` has no output, also the issue persists after a reboot. Did I misunderstand you?

**Comment by firecat53** [comment]
I think the only way we're going to solve this is if you setup a new real or
virtual machine, get keepmenu installed and working before anything else (other
than a window manager/DE), and then slowly start adding applications and
whatever tweaks/scripts you normally use until keepmenu stops working.

I spent 20 min the other day installing an Arch VM from scratch and as soon as I
had XFCE, dmenu, git, pip and base-devel installed, I was able to get keepmenu
working from git with a `pip install --user .` .

**Comment by firecat53** [comment]
Any progress on getting this working for you yet?

**Comment by tenklo** [comment]
I've been using tag 1.0.0, which kept working.
Just now I tried the main branch again, there is a new error:
```
Traceback (most recent call last):
  File "/home/karsten/.local/bin/keepmenu", line 5, in <module>
    from keepmenu.__main__ import main
  File "/home/karsten/.local/lib/python3.9/site-packages/keepmenu/__init__.py", line 102, in <module>
    reload_config()
  File "/home/karsten/.local/lib/python3.9/site-packages/keepmenu/__init__.py", line 75, in reload_config
    if "-l" in command:
UnboundLocalError: local variable 'command' referenced before assignment
```
Does this sound any easier to fix?

**Comment by firecat53** [comment]
It appears you don't have a `dmenu_command` option in your config.ini. You did
locate a bug which I can fix, but you likely would want to add that option so
you can add theming/configuration flags to your dmenu or Rofi commands.

**Comment by firecat53** [comment]
I did push a fix for the error you're seeing. However, you still should probably
have `dmenu_command` defined in config.ini.

There's not a new release yet, so you'll have to install from git and not from
pypi to see the changes.

**Comment by tenklo** [comment]
Thank you so much!
Everything seems to be working for now.
